description: LobeHub Prompts Testing Suite

# Default providers for testing - can be overridden in individual test configs
providers:
  - openai:gpt-4.1-mini

# Test configurations
tests:
  - promptfoo/translation.yaml
#  - promptfoo/summary-title.yaml
#  - promptfoo/language-detection.yaml
#  - promptfoo/emoji-picker.yaml
#  - promptfoo/knowledge-qa.yaml

# Output configuration
outputPath: promptfoo-results.json

# Default test settings
defaultTest:
  assert:
    - type: llm-rubric
      provider: openai:gpt-5-mini
      value: "The response should be relevant and well-formatted"
    - type: cost
      threshold: 0.01  # Maximum cost per test in USD

# Environment variables for API keys
env:
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}

# Evaluation settings
evaluateOptions:
  maxConcurrency: 5
  delay: 100

# TypeScript support
transforms:
  - "typescript"
